### ISSUE TITLE
Docs builds failing

### ISSUE THREAD

**Issue by gjoseph92** [gjoseph92/stackstac#151]
```python-traceback
Traceback (most recent call last):
  File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/docs/.pyenv/versions/3.8.6/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/stackstac/envs/149/lib/python3.8/site-packages/sphinx/__main__.py", line 13, in <module>
    from sphinx.cmd.build import main
  File "/home/docs/checkouts/readthedocs.org/user_builds/stackstac/envs/149/lib/python3.8/site-packages/sphinx/cmd/build.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/home/docs/checkouts/readthedocs.org/user_builds/stackstac/envs/149/lib/python3.8/site-packages/sphinx/application.py", line 43, in <module>
    from sphinx.registry import SphinxComponentRegistry
  File "/home/docs/checkouts/readthedocs.org/user_builds/stackstac/envs/149/lib/python3.8/site-packages/sphinx/registry.py", line 24, in <module>
    from sphinx.builders import Builder
  File "/home/docs/checkouts/readthedocs.org/user_builds/stackstac/envs/149/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 26, in <module>
    from sphinx.util import import_object, logging, progress_message, rst, status_iterator
  File "/home/docs/checkouts/readthedocs.org/user_builds/stackstac/envs/149/lib/python3.8/site-packages/sphinx/util/rst.py", line 21, in <module>
    from jinja2 import Environment, environmentfilter
ImportError: cannot import name 'environmentfilter' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/stackstac/envs/149/lib/python3.8/site-packages/jinja2/__init__.py)
```
https://readthedocs.org/projects/stackstac/builds/16790959/

jinja2 released a new version on April 28, could be it?

**Comment by aazuspan** [comment]
Check out https://github.com/sphinx-doc/sphinx/issues/10291. Pinning `Jinja2<3.1` works locally for me.
